Marker:
    type: entity
    table: marker
    indexes:
        IDX_82CF20FEF6471F30:
            columns:
                - pollution
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        lat:
            type: float
            nullable: true
            precision: 10
            scale: 0
        lng:
            type: float
            nullable: true
            precision: 10
            scale: 0
        login:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        ville:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        pays:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
    manyToOne:
        pollution:
            targetEntity: Pollution
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pollution:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
