Postmsg:
    type: entity
    table: postmsg
    indexes:
        IDX_454299B3F6471F30:
            columns:
                - pollution
        IDX_454299B366A7B847:
            columns:
                - tuser
        IDX_454299B314B78418:
            columns:
                - photo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        pseudo:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        message:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        date:
            type: datetime
            nullable: true
    manyToOne:
        pollution:
            targetEntity: Pollution
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pollution:
                    referencedColumnName: id
            orphanRemoval: false
        tuser:
            targetEntity: Tuser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tuser:
                    referencedColumnName: id
            orphanRemoval: false
        photo:
            targetEntity: Photo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                photo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
