Tuser:
    type: entity
    table: tuser
    indexes:
        IDX_66A7B847FA32C528:
            columns:
                - id_photo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        login:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        prenom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        adresse:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        codePostal:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: code_postal
        ville:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        tel:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        pseudo:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        type:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
        role:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
    manyToOne:
        idPhoto:
            targetEntity: Photo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_photo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
